apiVersion: v1
kind: ConfigMap
metadata:
  name: iotedge-spiffe-server
data:
  Config.toml: |
    socket_path = "/run/iotedge/sockets/api.sock"
    trust_domain = "iotedge"

    [jwt]
    key_type = "ES256"
    key_ttl = 300
    ttl = 10

    [trust-bundle]
    refresh_hint = 10

    [key-store]
    type = "Disk"
    [key-store.args]
    key_base_path = "."

    [catalog]
    type = "Memory"

    [server-agent-api]
    bind_address = "0.0.0.0"
    bind_port = 8443

    [node-attestation-config]
    type = "PSAT"
    [node-attestation-config.content]
    service_account_allow_list = ["iotedge-spiffe-agent"]
    audience = "iotedge-spiffe-server"
    cluster_name = "demo-cluster"
    allowed_node_label_keys = ["node-name"]
    allowed_pod_label_keys = ["pod-name"]
  
  ManagerConfig.toml: |
    trust_domain  = "SPIFFE ID trust domain"

    server_socket_path = "/run/iotedge/sockets/api.sock"

    # Entries
    [[entry]]
    spiffe_id = "1"
    spiffe_id_path = "agent"
    [entry.attestation_config]
    type = "NODE" 
    [entry.attestation_config.content]
    value = ["AGENTSERVICEACCOUNT:iotedge-spiffe-agent"]
    plugin = "PSAT"

    [[entry]]
    spiffe_id = "2"
    spiffe_id_path = "genericnode"
    [entry.attestation_config]
    type = "WORKLOAD" 
    [entry.attestation_config.content]
    value = ["PODLABELS:app:genericnode"]
    plugin = "K8S"
    parent_id = "1"
    [[other_identities]]
    type = "IOTHUB"
    content = {iot_hub_hostname = "myhub", device_id = "mydevice", module_id = "modid" }
    [[other_identities]]
    type = "CUSTOM"
    content = "full json here"

    [[entry]]
    spiffe_id = "3"
    spiffe_id_path = "mqttbroker"
    [entry.attestation_config]
    type = "WORKLOAD" 
    [entry.attestation_config.content]
    value = ["PODLABELS:app:mqttbroker"]
    plugin = "K8S"
    parent_id = "1"
